name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Copy macOS Screenshots to Linux Version
        run: |
          mkdir -p src/tests/visual.spec.ts-snapshots  # Ensure the snapshot directory exists
          if [ -f src/tests/visual.spec.ts-snapshots/aboutpage-darwin.png ]; then
            cp src/tests/visual.spec.ts-snapshots/aboutpage-darwin.png src/tests/visual.spec.ts-snapshots/aboutpage-linux.png
          fi
        continue-on-error: true  # Continue even if the file doesn't exist (avoid failing the build)    

      - name: Build the Next.js app
        run: npm run build

      - name: Run Playwright tests
        run: npx playwright test src/tests/visual.spec.ts